default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 1
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: web-clothes_development
test:
  <<: *default
  database: web-clothes_test
production:
  <<: *default
  database: web-clothes_production
  username: web-clothes
  password: <%= ENV['WEB-CLOTHES_DATABASE_PASSWORD'] %>
